app/views.py
from flask import Blueprint, render_template, flash,redirect,request,jsonify,url_for
from .models import Vacancy, Profile
#from models import db, Vacancy
from flask_login import login_required,current_user
from datetime import date
from . import db
from . forms import ProfileForm

views=Blueprint('views', __name__)

@views.route('/')
def home():
    #jobs=Jobs.query.filter_by(flash_sale=True)
    return render_template('home.html')



@views.route("/applications")
def applications():
    return render_template("applications.html")

@views.route("/Vacancies")
def list_vacancies():
    vacancies=Vacancy.query.all()
    return render_template("Vacancies.html", vacancies=vacancies)

@views.route('/vacancy/<int:vacancy_id>')
def vacancy_details(vacancy_id):
    vacancy=Vacancy.query.get_or_404(vacancy_id)
    return render_template('vacancy_details.html', vacancy=vacancy)

@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        email = form.email.data
        title = form.title.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        gender = form.gender.data
        dob = form.dob.data
        phone = form.phone.data
        alt_phone = form.alt_phone.data
        postal_address = form.postal_address.data
        postal_code = form.postal_code.data

        # Check for duplicate email 
        existing_profile = Profile.query.filter_by(email=email).first() 
        if existing_profile: 
           flash(f'A profile with this email already exists. Please use a different email.') 
           return render_template('profile.html', form=form)
        
        user_profile = Profile(
            email=email,
            title=title,
            first_name=first_name,
            last_name=last_name,
            gender=gender,
            dob=dob,
            phone=phone,
            alt_phone=alt_phone,
            postal_address=postal_address,
            postal_code=postal_code
        )
        
        try:
            db.session.add(user_profile)
            db.session.commit()
            flash(f'Records added successfully')
            return redirect(url_for('profile'))
        except Exception as e:
            print(e)
            flash(f'Profile not created, try again')
            form = ProfileForm()  # Reset/clear form fields
    
    return render_template('profile.html', form=form)

app/templates/Education.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

app/templates/Vacancies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Available Vacancies</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .vacancy { border: 1px solid #ddd; margin: 10px; padding: 10px; border-radius: 5px; }
        .button { margin-right: 10px; }
    </style>
</head>
<body>
    <h1>Available Vacancies</h1>
    {% for vacancy in vacancies %}
    <div class= "vacancy">
        <h2>{{ vacancy.title }}</h2>
        <p><strong>Department:</strong> {{ vacancy.department }} | <strong>Type:</strong> {{ vacancy.contract_type }}</p>
        <p>Posted: {{ vacancy.posted_date }} | Expires: {{ vacancy.expiry_date }}</p>
        <p>{{ vacancy.description[:200] }}...</p>
        <a class="button" href="{{ url_for('views.vacancy_details', vacancy_id=vacancy.id) }}">View Details</a>
        <a class="button" href="#">Download</a>
    </div>
    {% else %}
    <p>No vacancies available at the moment.</p>
    {% endfor %}
</body>
</html>

app/templates/applications.html
{% extends 'base.html' %}

{% block title %} Applications {% endblock %}

{% block body %}

<div class="menu-container">
    <div class="menu-item active">1. Profile</div>
    <div class="menu-item">2. Education</div>
    <div class="menu-item">3. Work Experience</div>
    <div class="menu-item">4. Referees</div>
    <div class="menu-item">5. Submit Application</div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
        
        <script src="" async defer></script>
        
        <script src="https://kit.fontawesome.com/e24507d923.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" />
    
        <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
       
    <title>Jobs | {%block title%} {%endblock%}</title>
    <body style="background-color: rgba(196, 199, 202, 0.99);">
      


        <!-- navbar section -->
        <nav class="navbar navbar-expand-lg" style="background-color: white;">
          <div class="container-fluid">
            <a class="navbar-brand" href="#" style="color: orange; font-size: 30px; margin-right: -2px;">
              <i class="fa-brands fa-amazon"></i>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/" style="font-family: cursive; font-size: 19px;">ODPC</a>
                </li>
    
                <li class="nav-item">
                  <a class="nav-link text-grey" href="#" style="font-size: 17px;">About Us</a>
                </li>
    
                <li class="nav-item">
                  <a class="nav-link text-grey" href="#" style="font-size: 17px;">Contact us</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link text-grey" href="Vacancies" style="font-size: 17px;">Vacancies</a>
                </li>

              </ul>
    
              <form class="d-flex" role="search" action="/search" style="margin-right: 170px;" method="POST">
                <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
                <button class="btn" type="submit">Search</button>
              </form>
            </div>
    
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    
              <li class="nav-item mx-2" id="items">
                
                
              </li>
              
              <li class="nav-item dropdown mx-2">
                <a class="nav-link dropdown-toggle text-grey" href="#" role="button", id="profileDropdown" 
                data-bs-toggle="dropdown" aria-hidden="false">
                  Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="profileDropdown">
    
                
                  {% if current_user.is_authenticated %}
                  <li><a class="dropdown-item" href="/profile/{{ current_user.id }}">Profile <i class="fa-solid fa-user"></i></a></li> 
                  <li><a class="dropdown-item" href="/logout">Log Out <i class="fa-solid fa-right-from-bracket"></i></a></li>
    
                  {% else %}
                  
                  <li><a class="dropdown-item" href="/login">Login <i class="fa-solid fa-right-to-bracket"></i></a></li>
    
                  {% endif %}
    
                </ul>
    
              </li>
    
            </ul>
    
    
          </div>
        </nav>
    
    
        {% for message in get_flashed_messages() %}
    
        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        
        </div>
        {% endfor %}
        <br>
    
        {% block body %}
    
    
        {% endblock %}
    
    
        <footer class="container-fluid  text-center p-2 mt-5" style="background-color: grey; color: white;">
          <a href="https://github.com/Frost-Codes" style="color: white;">Recruitment Portal</a> | <span>
            <i class="fa-sharp fa-regular fa-copyright"></i></span> ODPC | 2024 All rights reserved
    
        </footer>
    
        <script src="{{ url_for( 'static', filename='js/owl.carousel.min.js') }}"></script>
        <script src="{{ url_for( 'static', filename='js/all.min.js') }}"></script>
        <script src="{{ url_for( 'static', filename='js/jquery.js') }}"></script>
    
        <script src="{{ url_for( 'static', filename='js/myScript.js') }}"></script>
    
    </body>
</html>

app/templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" ></script>


    <script src="https://kit.fontawesome.com/e24507d923.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" />

    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}">

    <title>Vacancies | {% block title %} {% endblock %}</title>
</head>

<body>
    {% for message in get_flashed_messages() %}

    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    
    </div>
    {% endfor %}

    {% block body %}


    {% endblock %}
</body>

app/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="container text-center">
    <div class="row" style="margin: 10px;">
      <div class="col " style="margin: 3px;">
        <div class="list-group" id="right1">
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                <span class="link-name">Supermarket</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span class="link-name">Health & Beuty</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa-solid fa-comment"></i>                
                <span class="link-name">Home & Office</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-camera" aria-hidden="true"></i>
                <span class="link-name">Fashion</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-audio-description" aria-hidden="true"></i>
                <span class="link-name">Electronics</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-cubes" aria-hidden="true"></i>
                <span class="link-name">Gaming</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-child" aria-hidden="true"></i>
                <span class="link-name">Baby Products</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-bicycle" aria-hidden="true"></i>
                <span class="link-name">Sporting Goods</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-binoculars" aria-hidden="true"></i>
                <span class="link-name">Garden & Outdoor</span>
            </a>

        </div>
      </div>


      <div class="col-md-7" style="margin: 3px;">
        <img src="../static/images/center.gif" alt="" style="width: 600px; height: 365px; border-radius: 10px;">
      </div>
      <div class="col-md-2">
        <div class="row" style="background-color: white; border-radius: 10px;">
        
            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/help.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">HELP CENTER</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">Customer care</p>
                </div>
            </div>

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/return.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">EASY RETURN</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">Quick Refund</p>
                </div>
            </div>

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/payment.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">SELL ON AMAZON</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">FBA Program</p>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 12px;">
            <div class="col">
                <img src="../static/images/right2.gif" alt="" class="right2">
            </div>
        
        </div>
      </div>
    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px;">
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/techweek.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Tech Week</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/FreeDelivery.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Free Delivery</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/food.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Amazon Food</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/airtime.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Airtime & Bills</h6>
        </div>
 
    </div>
</div>

    </div>
</div>


{% endblock %}

app/templates/login.html
{% extends 'forms.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<!-- Login section start -->

<section class="base" id="base-login">
    <div class="base-content">
        <div class="form">
            <h3>
                Login to start <br> your job application.
            </h3>
            
            <hr class="first">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="email"><h4>Email Address</h4>{{ form.email }} <hr></div>
                <div class="password"><h4>Password</h4>{{ form.password }} <hr></div>

                <div class="buttons">
                    <a href="/signup"> Signup</a>
                    {{ form.submit() }}
                </div>


            </form>
        </div>
    </div>
</section>


{% endblock %}

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Form</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css') }}">
</head>
<body>
    <div class="container">
        {% with messages = get_flashed_messages() %} {% if messages %} 
        <div class="flash-messages" id="flash-messages"> 
            {% for message in messages %} 
            <div class="alert">{{ message }}
            </div> 
            {% endfor %} 
        </div> <script> setTimeout(function()
             { var flashMessages = document.getElementById('flash-messages'); flashMessages.classList.add('fade-out'); }, 3000); // 3000 milliseconds = 3 seconds </script> {% endif %} {% endwith %}
        <h3>My Account</h3>
        
        <div class="tabs">
            <div class="tab active">1. Profile</div>
            <div class="tab">2. Education</div>
            <div class="tab">3. Work Experience</div>
            <div class="tab">4. Referee</div>
            <div class="tab">5. Summary</div>
        </div>

        <p class="required-note">Fields marked with * are required</p>
    
        <form class="profile-form" method="POST" action="{{ url_for('views.profile') }}">
            {{ form.hidden_tag() }}
            <div class="form-row">
                <div class="form-group">
                    <label for="email">E-mail *</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    {{ form.title }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="first-name">First Name *</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="last-name">Last Name *</label>
                    {{ form.last_name }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="gender">Gender</label>
                    {{ form.gender }}
                </div>
                <div class="form-group">
                    <label for="dob">Date of Birth</label>
                    {{ form.dob }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="phone">Phone</label>
                    {{ form.phone }}
                </div>
                <div class="form-group">
                    <label for="alt-phone">Alternative Phone</label>
                    {{ form.alt_phone }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label for="postal-address">Postal Address</label>
                    {{ form.postal_address }}
                </div>
                <div class="form-group">
                    <label for="postal-code">Postal Code</label>
                    {{ form.postal_code }}
                </div>
            </div>
            <div class="button-group">
                <button class="save" type="submit">SAVE</button>
                <button class="next" type="button">NEXT</button>
            </div>
        </form>
    </div>
</body>
</html>

app/templates/signup.html
{% extends 'forms.html' %}

{% block title %} Sign Up {% endblock %}

{% block body %}

<!-- Sign Up section start -->

<section class="base" id="base-signup">
    <div class="base-content">
        <div class="form">
            <h3>
                Create an account <br>to make applications
            </h3>
            
            <hr class="first">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="email"><h4>Email Address</h4>{{ form.email }} <hr> </div>
                <div class="name"><h4>User Name</h4>{{ form.username }} <hr></div>
                <div class="password"><h4>Password</h4>{{ form.password1 }} <hr></div>
                <div class="password"><h4>Confirm Password</h4>{{ form.password2 }} <hr></div>

                <div class="buttons">
                    <a href="/login"> Login</a>
                    {{ form.submit() }}
                </div>


            </form>
        </div>
    </div>
</section>


{% endblock %}

app/templates/vacancy_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ vacancy.title }}</title>
</head>
<body>
    <h1>{{ vacancy.title }}</h1>
    <p><strong>Department:</strong> {{ vacancy.department }}</p>
    <p><strong>Contract Type:</strong> {{ vacancy.contract_type }}</p>
    <p><strong>Posted Date:</strong> {{ vacancy.posted_date }}</p>
    <p><strong>Expiry Date:</strong> {{ vacancy.expiry_date }}</p>
    <p>{{ vacancy.description }}</p>
    <a href="/">Back to Vacancies</a>
</body>
</html>